{% set name = "langchain-voyageai" %}
{% set version = "0.1.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/langchain_voyageai-{{ version }}.tar.gz
  sha256: 45f4f6de51b094328e6e2799b3673fc7069b532b4af0d308d1b5bc89920c59db

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pdm-backend
    - pip
  run:
    - pydantic <3,>=2
    - python >={{ python_min }},<4.0
    - langchain-core <1.0.0,>=0.3.29
    - voyageai <1,>=0.3.2

test:
  imports:
    - langchain_voyageai
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/langchain-ai/langchain
  summary: An integration package connecting VoyageAI and LangChain
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
