schema_version: 1

context:
  name: langchain-voyageai
  version: "0.4.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/langchain_voyageai-${{ version }}.tar.gz
  sha256: 294293b35f6973a965b521e51a1d1423d467921fc74ccfac2568ca92775201d1

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pdm-backend
    - pip
  run:
    - pydantic <3,>=2
    - python >=${{ python_min }},<4.0
    - langchain-core >=1.0.0
    - voyageai <1,>=0.4.1
tests:
  - python:
      imports:
        - langchain_voyageai
      pip_check: true
      python_version: ${{ python_min }}

about:
  summary: An integration package connecting VoyageAI and LangChain
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/langchain-ai/langchain

extra:
  recipe-maintainers:
    - jan-janssen
